### ISSUE TITLE
Crashes on "Open file"

### ISSUE THREAD

**Issue by stevenroose** [limetext/lime-qml#47]
Here are the logs:
https://gist.github.com/stevenroose/d788446323d99694a484212a3d7635e8

I'm on Arch using GNOME 3 that uses Wayland.

**Comment by ricochet1k** [comment]
So, what's weird about this is that I always use Arch on GNOME 3, and I switch back and forth from Wayland to X as various bugs annoy me. I've never seen a segfault like this.

**Comment by ricochet1k** [comment]
Do you have custom versions of gtk3, qt, go, etc. installed? The error mentions something about a bad GDK/X11 window, like GDK is expecting to get an X11 window. In any case, it appears that the error message has nothing to do with LimeText since we never talk directly to X11 or Wayland. But post your findings if you figure out how to fix it, for future reference.

**Comment by stevenroose** [comment]
@ricochet1k Oh yeah you were right, it was due to my fucked up setup. It's fixed now (I just use X and ditched Wayland)!
